In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/data.csv')

In [3]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [4]:
string_columns = list(df.dtypes[df.dtypes==object].index)

In [5]:
for col in string_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [6]:
df.head()

make       model  year             engine_fuel_type  engine_hp  \
0  bmw  1_series_m  2011  premium_unleaded_(required)      335.0   
1  bmw    1_series  2011  premium_unleaded_(required)      300.0   
2  bmw    1_series  2011  premium_unleaded_(required)      300.0   
3  bmw    1_series  2011  premium_unleaded_(required)      230.0   
4  bmw    1_series  2011  premium_unleaded_(required)      230.0   

   engine_cylinders transmission_type     driven_wheels  number_of_doors  \
0               6.0            manual  rear_wheel_drive              2.0   
1               6.0            manual  rear_wheel_drive              2.0   
2               6.0            manual  rear_wheel_drive              2.0   
3               6.0            manual  rear_wheel_drive              2.0   
4               6.0            manual  rear_wheel_drive              2.0   

                         market_category vehicle_size vehicle_style  \
0  factory_tuner,luxury,high-performance      compact         coupe   
1                     luxury,performance      compact   convertible   
2                luxury,high-performance      compact         coupe   
3                     luxury,performance      compact         coupe   
4                                 luxury      compact   convertible   

   highway_mpg  city_mpg  popularity   msrp  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [7]:
df.engine_hp = df.engine_hp.fillna(250)
df.number_of_doors = df.number_of_doors.fillna(4)
df.engine_cylinders = df.engine_cylinders.fillna(6)

In [8]:
n = len(df)
n_train = int(len(df) * 0.6)
n_test = n - n_train
idx = np.arange(n)

In [9]:
np.random.seed(2)
np.random.shuffle(idx)

In [10]:
idx

array([2735, 6720, 5878, ..., 6637, 2575, 7336])

In [11]:
df_train = df.iloc[idx[:n_train]]
df_test = df.iloc[idx[n_train:]]

In [12]:
df_test

make         model  year                engine_fuel_type  \
5284     rolls-royce         ghost  2014     premium_unleaded_(required)   
2420      volkswagen            cc  2017  premium_unleaded_(recommended)   
2779       chevrolet      colorado  2015                regular_unleaded   
3708   mercedes-benz       e-class  2017     premium_unleaded_(required)   
4794            ford         focus  2017        flex-fuel_(unleaded/e85)   
...              ...           ...   ...                             ...   
2514       chevrolet     chevy_van  1998                regular_unleaded   
11798         subaru  xv_crosstrek  2014                regular_unleaded   
6637           dodge        magnum  2006                regular_unleaded   
2575           honda         civic  2016                regular_unleaded   
7336          subaru       outback  2015                regular_unleaded   

       engine_hp  engine_cylinders transmission_type      driven_wheels  \
5284       563.0              12.0         automatic   rear_wheel_drive   
2420       200.0               4.0  automated_manual  front_wheel_drive   
2779       200.0               4.0         automatic   four_wheel_drive   
3708       241.0               4.0         automatic    all_wheel_drive   
4794       160.0               4.0            manual  front_wheel_drive   
...          ...               ...               ...                ...   
2514       200.0               6.0         automatic   rear_wheel_drive   
11798      160.0               4.0         automatic    all_wheel_drive   
6637       250.0               6.0         automatic    all_wheel_drive   
2575       174.0               4.0         automatic  front_wheel_drive   
7336       256.0               6.0         automatic    all_wheel_drive   

       number_of_doors            market_category vehicle_size  \
5284               4.0  exotic,luxury,performance        large   
2420               4.0                performance      midsize   
2779               4.0                        NaN      compact   
3708               4.0                     luxury      midsize   
4794               4.0                  flex_fuel      compact   
...                ...                        ...          ...   
2514               3.0                        NaN      midsize   
11798              4.0           crossover,hybrid      compact   
6637               4.0                        NaN        large   
2575               4.0                        NaN      midsize   
7336               4.0                  crossover      midsize   

             vehicle_style  highway_mpg  city_mpg  popularity    msrp  
5284                 sedan           21        13          86  303300  
2420                 sedan           31        22         873   37820  
2779   extended_cab_pickup           25        19        1385   26885  
3708                 sedan           29        22         617   54650  
4794                 sedan           36        26        5657   16775  
...                    ...          ...       ...         ...     ...  
2514             cargo_van           18        13        1385    2052  
11798              4dr_suv           33        29         640   25995  
6637                 wagon           22        15        1851   29100  
2575                 sedan           42        31        2202   22200  
7336               4dr_suv           27        20         640   32995  

[4766 rows x 16 columns]

In [13]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [14]:
y_train = np.log1p(df_train.msrp.values)
y_test = np.log1p(df_test.msrp.values)

In [15]:
del df_train['msrp']
del df_test['msrp']

In [16]:
df_train = df_train[list(df_train.dtypes[df_train.dtypes != object].index)]


In [17]:
df_train = np.array(df_train)
df_train = np.hstack((np.ones([df_train.shape[0],1], df_train.dtype), df_train))

In [18]:
df_train

array([[1.000e+00, 2.008e+03, 1.480e+02, ..., 3.300e+01, 2.400e+01,
        1.385e+03],
       [1.000e+00, 2.012e+03, 1.320e+02, ..., 3.200e+01, 2.500e+01,
        2.031e+03],
       [1.000e+00, 2.016e+03, 1.480e+02, ..., 3.700e+01, 2.800e+01,
        6.400e+02],
       ...,
       [1.000e+00, 2.015e+03, 3.000e+02, ..., 3.100e+01, 2.000e+01,
        3.916e+03],
       [1.000e+00, 2.015e+03, 2.100e+02, ..., 3.000e+01, 2.400e+01,
        8.730e+02],
       [1.000e+00, 2.015e+03, 2.850e+02, ..., 2.200e+01, 1.700e+01,
        5.490e+02]])

In [19]:
df_test = df_test[list(df_test.dtypes[df_test.dtypes != object].index)]
df_test = np.array(df_test)
df_test = np.hstack((np.ones([df_test.shape[0],1]), df_test))

In [20]:
y_train = np.array(y_train)

In [21]:
y_test = np.array(y_test)

In [22]:
y_train.reshape(y_train.shape[0], 1)
y_test.reshape(y_test.shape[0], 1)

array([[12.62248099],
       [10.54061978],
       [10.19936098],
       ...,
       [10.27852782],
       [10.00789261],
       [10.40414162]])

In [23]:
df_train

array([[1.000e+00, 2.008e+03, 1.480e+02, ..., 3.300e+01, 2.400e+01,
        1.385e+03],
       [1.000e+00, 2.012e+03, 1.320e+02, ..., 3.200e+01, 2.500e+01,
        2.031e+03],
       [1.000e+00, 2.016e+03, 1.480e+02, ..., 3.700e+01, 2.800e+01,
        6.400e+02],
       ...,
       [1.000e+00, 2.015e+03, 3.000e+02, ..., 3.100e+01, 2.000e+01,
        3.916e+03],
       [1.000e+00, 2.015e+03, 2.100e+02, ..., 3.000e+01, 2.400e+01,
        8.730e+02],
       [1.000e+00, 2.015e+03, 2.850e+02, ..., 2.200e+01, 1.700e+01,
        5.490e+02]])

In [24]:
w = (df_train.T).dot(df_train)
w

array([[7.14800000e+03, 1.43694650e+07, 1.78020500e+06, 4.02320000e+04,
        2.45320000e+04, 1.90739000e+05, 1.41382000e+05, 1.10125190e+07],
       [1.43694650e+07, 2.88870338e+10, 3.58084982e+09, 8.08737580e+07,
        4.93289060e+07, 3.83563645e+08, 2.84316026e+08, 2.21444731e+10],
       [1.78020500e+06, 3.58084982e+09, 5.28455577e+08, 1.10761770e+07,
        6.04395500e+06, 4.50710700e+07, 3.27975960e+07, 2.78672612e+09],
       [4.02320000e+04, 8.08737580e+07, 1.10761770e+07, 2.48936000e+05,
        1.36538000e+05, 1.00385400e+06, 7.29149000e+05, 6.27463260e+07],
       [2.45320000e+04, 4.93289060e+07, 6.04395500e+06, 1.36538000e+05,
        8.97800000e+04, 6.61074000e+05, 4.92020000e+05, 3.73160730e+07],
       [1.90739000e+05, 3.83563645e+08, 4.50710700e+07, 1.00385400e+06,
        6.61074000e+05, 5.70590500e+06, 4.29213100e+06, 2.92363762e+08],
       [1.41382000e+05, 2.84316026e+08, 3.27975960e+07, 7.29149000e+05,
        4.92020000e+05, 4.29213100e+06, 3.39128200e+06, 2.

In [25]:
w = np.linalg.inv(w)

In [26]:
w=w.dot(df_train.T)

In [27]:
w=w.dot(y_train)

In [28]:
print(w)

[-1.80730668e+02  9.43167033e-02  3.89803398e-03  6.25042650e-02
 -1.72436187e-02 -2.31249181e-03  5.25853325e-03 -4.89320043e-05]


In [32]:
predict = df_test.dot(w)

In [36]:
predict = np.expm1(predict)

In [38]:
def rmse(y, y_pred):
    error = y - y_pred
    se = error**2
    mse = se.mean()
    rmse = np.sqrt(mse)
    return rmse

In [42]:
rmse(predict, np.expm1(y_test))

35916.123889776885

2.23606797749979